version: '2'
services:
  influxdb:
    image: library/influxdb:1.1.1
    container_name: influxdb
    ports:
      - 8083:8083 # Web
      - 8086:8086 # TCP
    environment:
      - INFLUXDB_ADMIN_ENABLED=true
  grafana:
    image: grafana/grafana:4.1.1
    container_name: grafana
    ports:
      - 3000:3000 # Web
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_SECURITY_DISABLE_GRAVATAR=true
      - GF_USERS_ALLOW_SIGN_UP=false
    depends_on:
      - influxdb
    links:
      - influxdb:influxdb